=head1 NOMBRE

perlbook - Información sobre libros de Perl

=head1 DESCRIPCIÓN

El libro del Camello, oficialmente conocido como I<Programando en Perl, Tercera Edición>, de Larry Wall y otros, es la referencia definitiva sobre casi todo el lenguaje Perl.  Puede pedir éste y otros libros Perl a O'Reilly & Asociados, 1-800-998-9938.  Llamada internacional +1 707 829 0515.  Si encuentra un formulario de pedido de O'Reilly, puede enviarlo por fax a +1 707 829 0104.
Si puede conectarse por web, puede encontrar un formulario en L<http://www.oreilly.com/>.

Otros libros sobre Perl de otras editoriales y autores pueden encontrarse en L<perlfaq2> o en la web L<http://books.perl.org/>.
