=encoding utf8

=head1 NOMBRE

perlboot - Enlaza a la información sobre programación orientada a objetos, en Perl

=head1 DESCRIPCIÓN

Para obtener más información sobre la programación orientada a objetos en Perl, vea L<perlootut> y L<perlobj>.

(Los documentos anteriores reemplazan al tutorial que anteriormente estaba aquí).

=cut
