=encoding utf8

=head1 NOMBRE

perlrepository - Enlaces a la información actual sobre el repositorio de código Perl

=head1 DESCRIPCIÓN

El código fuente de Perl se almacena en un repositorio Git.

Vea L<perlhack> por una explicación del desarrollo de Perl, incluyendo la L<Super guía rápida del parcheo|perlhack/SUPER GUÍA RÁPIDA DEL PARCHEO> para ver cómo crear y entregar un pequeño parche.

Vea L<perlgit> para una detallada información sobre el repositorio Git de Perl.

(Los documentos anteriores reemplazan la información que antes se encontraba en este documento).
