=head1 NOMBRE

perllexwarn - Advertencias léxicas de Perl

=head1 DESCRIPCIÓN

Perl v5.6.0 presentó control lexico sobre la gestión de advertencias por categoría.  El pragma C<warnings> reemplaza, generalmente, a la bandera de línea de comandos B<-w>.  La documentación sobre el uso de advertencias léxicas, antes localizada parcialmente en este documento, se encuentra ahora en la documentación de L<warnings>.

