=encoding utf8

=head1 NOMBRE

perltooc - Documento suprimido

=head1 DESCRIPCIÓN

Para obtener más información sobre la programación orientada a objetos en
Perl, vea L<perlootut> y L<perlobj>.

=cut

=head1 TRADUCTORES

=over

=item * Joaquín Ferrero (Tech Lead)

=item * Enrique Nell (Language Lead)

=back

