=head1 NOMBRE

perltodo - Lista de tareas pendientes de Perl

=head1 DESCRIPCIÓN

Ya no instalamos la lista de tareas pendientes de Perl 5 como una página de
documentación; la instantánea instalada quedaba obsoleta al poco tiempo, por lo
que no era de mucha utilidad. Puede ver la lista actual de tareas pendientes de
Perl 5 en el repositorio git:
L<http://perl5.git.perl.org/perl.git/blob/HEAD:/Porting/todo.pod>


=head1 TRADUCTORES

=over

=item * Joaquín Ferrero (Tech Lead)

=item * Enrique Nell (Language Lead)

=back

