=head1 NOMBRE

perltooc - Documento suprimido

=head1 DESCRIPCIÓN

Para obtener más información sobre la programación orientada a objetos en Perl,
vea L<perlootut> y L<perlobj>.

=cut

=head1 TRADUCTORES

=over

=item * Joaquí­n Ferrero (Tech Lead), C< explorer + POD2ES at joaquinferrero.com >

=item * Enrique Nell (Language Lead), C< blas.gordon + POD2ES at gmail.com >

=back

