=head1 NOMBRE

perlbook - Libros sobre Perl

=head1 DESCRIPCIÓN

La referencia definitiva es el "Libro del Camello" (camello arábigo, o
dromedario), conocido oficialmente como I<Programming Perl, Third Edition>, de
Larry Wall et al., que cubre prácticamente todo el lenguaje Perl. Puede
encargar este libro (y otros libros sobre Perl) a O'Reilly & Associates, a
través del número 1-800-998-9938. El número de teléfono local y para llamadas
internacionales es +1 707 829 0515. Si dispone de un formulario de pedido de
O'Reilly, puede enviarlo por fax a través del número +1 707 829 0104. También
puede utilizar un formulario de pedido en línea en L<http://www.oreilly.com/>.

En L<perlfaq2> y en L<http://books.perl.org/> encontrará referencias a más
libros sobre Perl de otros autores (y otras editoriales).


=head1 TRADUCTORES

=over

=item * Joaquín Ferrero (Tech Lead), C< explorer + POD2ES at joaquinferrero.com >

=item * Enrique Nell (Language Lead), C< blas.gordon + POD2ES at gmail.com >

=back
